### ISSUE TITLE
Performance.

### ISSUE THREAD

**Issue by JimBobSquarePants** [BitMiracle/libjpeg.net#1]
Hi there,

I've been experimenting with this library in an effort to create an cross platform imaging library for corefx and I've hit a few issues with performance. 

Encoding and decoding a 3648 x 2736 image on a 12 core Intel(R) Xeon @ 3.20 Ghz. is taking me around 5-6 seconds where doing the equivalent with `System.Drawing` takes ~400ms.

I found an old comment in a blog post related to performance but I haven't seen any related commits in the repo.

http://bitmiracle.com/blog/libjpeg-net-is-ready-for-download

I've had a dig around the code to see what is going on but I found it very difficult to follow due to the formatting and code inconsistency, especially in the classic folder. 

Do you have any plans to improve performance or do you know of any parts within the code that might be contributing to the poor performance that I should look at?

Kindest Regards

James

The image in question.

![9bd24b20-bed5-11e5-84fd-15e2a83e3eb3](https://cloud.githubusercontent.com/assets/385879/12465890/97d7e124-c024-11e5-8e7a-f10823bdeab5.JPG)

**Comment by Bobrovsky** [comment]
Hello James,

I don't know about any specific place in the code that is slow. The code is not that slow for us to justify profiling and improvement costs. We, you and probably someone else will be happy to have faster code but so far no one spent some time improving the library performance.

Not sure what you mean when talking about inconsistency. 

The library code is as close to C code of the original libjpeg library as possible. We changed as little as possible because we needed something as fast as possible. We didn't change design (not exactly perfect) of the original code.

You are welcome to improve the library in any area. We will be happy to receive pull requests from you.

**Comment by JimBobSquarePants** [comment]
Hi Sergey,

Thanks for such a swift response. I appreciate that.

I guess most users haven't attempted to push the library as I have. When decoding/encoding small images it's quick enough to not cause concern but as soon as we reach dimensions such as the example image the slowdown is apparent.

The copying of the original C is a great part of what I meant by code inconsistency. There are classes throughout the solution written with different naming conventions, some of which are hard to determine their functionality. I don't read C well at all so I find it very difficult to follow despite my proficiency in C#. This makes it more difficult for me to contribute.

I don't think the original C design will lend itself to C# either in terms of performance as we don't then take advantage of some of the benefits C# and the .NET framework have to offer. There are certainly, it seems to me, a lot more classes involved than there should be.

I'll see what I can do to improve the library. Thanks for writing and sharing it.
